# Generated by Django 3.1.1 on 2020-10-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201013_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
