# Generated by Django 3.1.1 on 2020-10-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201019_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/avatar.png', null=True, upload_to='images/'),
        ),
    ]
